name: "Auth E2E"
description: "Single node with authentication service enabled"

# Enable auth service managed by Merobox
auth_service: true
force_pull_image: true 
# Node configuration
nodes:
  count: 1
  base_port: 2428
  base_rpc_port: 2528
  chain_id: "testnet-1"
  prefix: "calimero-node"

steps:
  - name: "Wait for node startup"
    type: "wait"
    seconds: 5
    message: "Waiting for node to fully start with auth service..."
  - name: "Install demo application"
    type: "install_application"
    node: "calimero-node-1"
    path: "tests/assets/kv_store.wasm"
    dev: true


