name: e2e

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Build auth image with our frontend (embedded)
        run: |
          docker build -f Dockerfile.auth.overlay -t ghcr.io/calimero-network/mero-auth:frontend-$GITHUB_SHA .

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Bootstrap Merobox with Auth (custom image)
        run: |
          npx @calimero-network/merobox-js bootstrap run workflow.yml --auth-service --auth-image ghcr.io/calimero-network/mero-auth:frontend-$GITHUB_SHA
        env:
          CI: true

      - name: Run e2e tests (merobox-managed)
        env:
          PW_BASE_URL: http://node1.127.0.0.1.nip.io
          MEROBOX_EXTERNAL: "1"
          CI: true
        run: pnpm exec playwright test --reporter=html

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7


